---
- name: Ensure systemd-resolved is running
  systemd:
    name: systemd-resolved
    state: started
    enabled: yes

- name: Configure systemd-resolved to use configurable DNS
  lineinfile:
    path: /etc/systemd/resolved.conf
    regexp: '^#?DNS='
    line: 'DNS={{ dns_servers | join(" ") }}'
    state: present

- name: Restart systemd-resolved service
  systemd:
    name: systemd-resolved
    state: restarted
