---
# tasks/setup-kernel.yml
- name: Create Kubernetes kernel modules config file
  copy:
    content: |
      overlay
      br_netfilter
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Attempt to load overlay module
  shell: modprobe overlay || true
  changed_when: false

- name: Attempt to load br_netfilter module
  shell: modprobe br_netfilter || true
  changed_when: false

- name: Create Kubernetes sysctl config file
  copy:
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'
  register: sysctl_conf

- name: Apply sysctl changes
  command: sysctl --system
  when: sysctl_conf.changed

- name: Check loaded modules
  shell: "lsmod | grep -E 'overlay|br_netfilter' || echo 'Modules may be built into kernel'"
  register: modules_check
  changed_when: false

- name: Display module status
  debug:
    var: modules_check.stdout_lines
