---
all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            controlplane:
              ansible_host: 10.203.146.138
        workers:
          hosts:
            node01:
              ansible_host: 10.203.146.31
            node02:
              ansible_host: 10.203.146.165
            node03:
              ansible_host: 10.203.146.249
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_ssh_private_key_file: /home/bl/.ssh/id_rsa_provisioning
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
