---
all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            controlplane:
              ansible_host: 10.203.146.16
        workers:
          hosts:
            node01:
              ansible_host: 10.203.146.150
            node02:
              ansible_host: 10.203.146.223
            node03:
              ansible_host: 10.203.146.125
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
