---
all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            controlplane:
              ansible_host: 10.203.146.7
        workers:
          hosts:
            node01:
              ansible_host: 10.203.146.55
            node02:
              ansible_host: 10.203.146.254
            node03:
              ansible_host: 10.203.146.131
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_ssh_private_key_file: /home/bl/.ssh/id_rsa_provisioning
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
