---
all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            controlplane:
              ansible_host: 10.57.249.3
        workers:
          hosts:
            node01:
              ansible_host: 10.57.249.58
            node02:
              ansible_host: 10.57.249.184
            node03:
              ansible_host: 10.57.249.34
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_ssh_private_key_file: /home/bl/.ssh/id_rsa_provisioning
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
