---
all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            controlplane:
              ansible_host: 10.203.146.166
        workers:
          hosts:
            node01:
              ansible_host: 10.203.146.180
            node02:
              ansible_host: 10.203.146.62
            node03:
              ansible_host: 10.203.146.185
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
