[postgres_primary]
pg-primary ansible_host=10.203.146.218

[postgres_replicas]
pg-replica1 ansible_host=10.203.146.159
pg-replica2 ansible_host=10.203.146.95

[postgres_lb]
pg-lb ansible_host=10.203.146.72

[postgres:children]
postgres_primary
postgres_replicas
postgres_lb

[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
