---
all:
  children:
    rqlite_cluster:
      children:
        rqlite_leader:
          hosts:
            rqlite1:
              ansible_host: 10.57.249.162
        rqlite_followers:
          hosts:
            rqlite2:
              ansible_host: 10.57.249.245
            rqlite3:
              ansible_host: 10.57.249.178
      vars:
        rqlite_nodes:
          - rqlite1
          - rqlite2
          - rqlite3
  vars:
    ansible_user: ubuntu
    ansible_become: yes
    ansible_ssh_private_key_file: /home/bl/.ssh/id_rsa_provisioning
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
