---
# Ansible playbook for tearing down an rqlite cluster
# Run with: ansible-playbook -i inventory.yml teardown-rqlite.yml -e "node_ips=10.203.146.136,10.203.146.91,10.203.146.232 leader_ip=10.203.146.232 ansible_user=ubuntu"

- name: Process input parameters and set up host groups
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Validate required variables are provided
      fail:
        msg: "Required variables 'node_ips' and 'leader_ip' must be provided"
      when: node_ips is not defined or leader_ip is not defined

    - name: Create array of IPs from comma-separated string
      set_fact:
        ip_list: "{{ node_ips.split(',') }}"

    - name: Verify leader_ip is in the node_ips list
      fail:
        msg: "Leader IP ({{ leader_ip }}) must be included in the list of node IPs"
      when: leader_ip not in ip_list

    - name: Add leader node to inventory
      add_host:
        name: "leader"
        ansible_host: "{{ leader_ip }}"
        node_id: "{{ ip_list.index(leader_ip) + 1 }}"
        groups: "rqlite_leader,rqlite_cluster"

    # Explicitly handle up to 2 follower nodes
    - name: Add first follower node if it exists
      add_host:
        name: "follower1"
        ansible_host: "{{ item }}"
        node_id: "{{ ip_list.index(item) + 1 }}"
        groups: "rqlite_followers,rqlite_cluster"
      with_items: "{{ ip_list }}"
      when: item != leader_ip
      run_once: true
      ignore_errors: yes

    - name: Add second follower node if it exists
      add_host:
        name: "follower2"
        ansible_host: "{{ item }}"
        node_id: "{{ ip_list.index(item) + 1 }}"
        groups: "rqlite_followers,rqlite_cluster"
      with_items: "{{ ip_list }}"
      when: 
        - item != leader_ip 
        - item != (hostvars['follower1']['ansible_host'] | default(''))
      run_once: true
      ignore_errors: yes

    - name: Display hosts that will be cleaned up
      debug:
        msg: |
          Preparing to remove rqlite from the following hosts:
          - Leader: {{ hostvars['leader']['ansible_host'] }}
          - Followers: {{ groups['rqlite_followers'] | map('extract', hostvars, ['ansible_host']) | join(', ') }}
          
          WARNING: This will completely remove rqlite and all its data from these servers.
          To cancel, press Ctrl+C now.

    - name: Pause for confirmation
      pause:
        prompt: "Press Enter to continue with the teardown process, or Ctrl+C to abort"
        seconds: 10

- name: Tear down rqlite on all nodes
  hosts: rqlite_cluster
  gather_facts: yes
  become: yes
  vars:
    rqlite_data_dir: "/home/{{ ansible_user }}/data"
    rqlite_extract_dir: "/opt/rqlite"
    
  tasks:
    - name: Stop and disable rqlited service
      systemd:
        name: rqlited
        state: stopped
        enabled: no
      ignore_errors: yes
      
    - name: Remove rqlited service file
      file:
        path: /etc/systemd/system/rqlited.service
        state: absent
      
    - name: Run daemon-reload to update systemd
      systemd:
        daemon_reload: yes
      
    - name: Remove rqlite binaries
      file:
        path: "/usr/local/bin/{{ item }}"
        state: absent
      with_items:
        - rqlited
        - rqlite
    
    - name: Remove rqlite data directory
      file:
        path: "{{ rqlite_data_dir }}"
        state: absent
      
    - name: Remove rqlite extract directory
      file:
        path: "{{ rqlite_extract_dir }}"
        state: absent
    
    - name: Close firewall ports (UFW)
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
        delete: yes
      with_items:
        - 4001  # Default HTTP port
        - 4002  # Default Raft port
      when: ansible_os_family == "Debian"
      ignore_errors: yes  # In case UFW isn't installed
    
    - name: Close firewall ports (firewalld)
      firewalld:
        port: "{{ item }}/tcp"
        permanent: yes
        state: disabled
      with_items:
        - 4001  # Default HTTP port
        - 4002  # Default Raft port
      when: ansible_os_family == "RedHat"
      ignore_errors: yes  # In case firewalld isn't installed

- name: Verify teardown is complete
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Display completion message
      debug:
        msg: |
          Teardown Complete
          
          rqlite has been completely removed from:
          - Leader: {{ hostvars['leader']['ansible_host'] }}
          - Followers: {{ groups['rqlite_followers'] | map('extract', hostvars, ['ansible_host']) | join(', ') }}
          
          The following items have been removed:
          - rqlite service
          - rqlite binaries
          - rqlite data directories
          - Firewall rules for rqlite
